export const ageOptions = Array.from({ length: 46 }, (_, i) => 20 + i);

export const maritalStatusOptions = [
  "single",
  "Married",
  "Unmarried",
  "Divorced",
  "Awaiting Divorce",
  "Widow",
];

export const kidsOptions = ["Yes", "No", "Doesn't matter"];

export const heightOptions = [
  `4'10" (147 cm)`,
  `4'11" (150 cm)`,
  `5'0" (152 cm)`,
  `5'1" (155 cm)`,
  `5'2" (157 cm)`,
  `5'3" (160 cm)`,
  `5'4" (163 cm)`,
  `5'5" (165 cm)`,
  `5'6" (168 cm)`,
  `5'7" (170 cm)`,
  `5'8" (173 cm)`,
  `5'9" (175 cm)`,
  `5'10" (178 cm)`,
  `5'11" (180 cm)`,
  `6'0" (183 cm)`,
  `6'1" (185 cm)`,
  `6'2" (188 cm)`,
  `6'3" (191 cm)`,
  `6'4" (193 cm)`,
  `6'5" (196 cm)`,
];

export const religionOptions = [
  "Hindu",
  "Muslim",
  "Christian",
  "Sikh",
  "Jain",
  "Parsi",
  "Buddhist",
  "Jewish",
  "Other",
];

export const casteOptions = ["General", "OBC", "SC", "ST", "Others"];

export const motherTongueOptions = [
  "Hindi",
  "English",
  "Bengali",
  "Gujarati",
  "Malyalam",
  "Kannada",
  "Telgu",
  "Punjabi",
  "Haryanvi",
  "Marathi",
  "Sindhi",
  "Urdu",
  "Tamil",
  "Bhojpuri",
  "Rajasthani",
  "Nepali",
  "Other",
];

export const communityOptions = [
  "Jat",
  "Gurjar",
  "Gujjar",
  "Baniya",
  "Pandit",
  "Brahmin",
  "Thakur",
  "Rajput",
  "Yadav",
  "Kayastha",
  "Chauhan",
  "Choudhary",
  "Jatav",
  "Chhetri",
  "Chaurasia",
  "Kamboj",
  "Kashyap",
  "Himachali",
  "Garwhali-Kumaon",
  "Garwhali",
  "Punjabi",
  "Ahir",
  "Tyagi",
  "Chamar",
  "Dhobi",
  "Khatri",
  "Kshatriya",
  "Kushwaha",
  "Lingayat",
  "Kumhar",
  "Vaishnav",
  "Halwai",
  "Varshney",
  "Aryasamaj ",
  "Others  ",
];

export const disabilityOptions = ["Yes", "No", "Doesn't Matter", "Other"];

export const stateOptions = [
  "Delhi- NCR",
  "Haryana",
  "Uttar Pradesh",
  "Uttarakhand",
  "Himachal Pradesh",
  "Punjab",
  "Rajasthan",
  "Madhya-Pradesh",
  "Odisha",
  "Tamil Nadu",
  "Karnataka",
  "Kerela",
  "Andhra-Pradesh",
  "Telangana",
  "Jammu & Kashmir",
  "Maharashtra",
  "Lakshadweep",
  "Jharkhand",
  "Assam",
  "Goa",
  "Bihar",
  "Arunachal Pradesh",
  "Gujarat",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Sikkim",
  "Tripura",
  "West Bengal",
];

export const metroCitiesOptions = [
  "Noida",
  "Gurgaon",
  "Ghaiziabad",
  "Faridabad",
  "Greater Noida",
  "Meerut",
  "Ahmedabad",
  "Hyderabad",
  "Jaipur",
  "Jodhpur",
  "Mumbai",
  "Pune",
  "Nagpur",
  "Aurangabad",
  "Nasik",
  "Goa",
  "Bangalore",
  "Chennai",
  "Coimbatore",
  "Chandigarh",
  "Mohali",
  "Panchkula",
  "Shimla",
  "Manali",
  "Dehradun",
  "Mussorie",
  "Kolkata",
  "Srinagar",
  "Indore",
  "Bhopal",
  "Lucknow",
  "Baroda",
  "Vadodra",
  "Surat",
  "Jamnagar",
  "Jammu",
  "Udhampur",
  "Kota",
  "Udaipur",
  "Neemrana",
  "Bhiwadi",
  "Alwar",
  "Bikaner",
  "Jalandhar",
  "Ludhiana",
  "Amritsar",
  "Mysore",
  "Bhuwaneshwar",
  "Nainital",
  "Hamirpur- HP",
  "Mandi-HP",
  "Bilaspur- HP",
  "Dharamshala-HP",
  "Bhuntar-HP",
  "Kullu",
  "Agra",
  "Mathura",
  "Aligarh",
  "Palwal",
  "Ayodhya",
  "Bareily",
  "Shamli",
  "Saharanpur",
  "Bijnor",
  "Moradabad",
  "Rohtak",
  "Karnal",
  "Hisar",
  "Ambala",
  "Panipat",
  "Sonepat",
  "Sirsa",
];

export const countryOptions = [
  "India",
  "USA",
  "UK",
  "Canada",
  "Dubai",
  "New Zealand",
  "Australia",
  "Germany",
  "France",
  "Saudi Arabia",
  "Qatar",
  "Abu Dhabi",
  "Ireland",
  "Singapore",
  "Mauritius",
  "Sri Lanka",
  "Bangladesh",
  "Bhutan",
  "Russia",
  "China",
  "Denmark",
  "Poland",
  "Latvia",
  "Sweden",
  "Italy",
  "Spain",
  "Norway",
  "Belgium",
  "Turkey",
  "Ukraine",
  "South Korea",
  "UAE",
  "Afghanistan",
  "Finland",
  "Greece",
  "Iceland",
  "Hongkong",
  "Hungary",
  "Iran",
  "Indonesia",
  "Israel",
  "Japan",
  "Jordan",
  "Luxembourg",
  "Maldives",
  "Malaysia",
  "Mexico",
  "Monaco",
  "Netherland",
  "Nigeria",
  "Nepal",
  "Philippines",
  "South Africa",
  "Switzerland",
  "Thailand",
  "Other",
];

export const incomeOptions = [
  "Select Income",
  "Rs 1 Lacs to Rs 5 Lacs",
  "Rs 5 Lacs to Rs 10 Lacs",
  "Rs 10 Lacs to Rs 15 Lacs",
  "Rs 15 Lacs to Rs 20 Lacs",
  "Rs 20 Lacs to Rs 30 Lacs",
  "Rs 30 Lacs to Rs 50 Lacs",
  "Rs 50 Lacs to Rs 1 Crore",
  "Rs 1 Crore to Rs 10 Crore",
  "Rs 10 Crore + ( Own Business )",
];

export const educationOptions = [
  "School Passout",
  "College Passout",
  "Professional Degree",
  "Bachelors Degree",
  "Masters Degree",
  "Certification",
  "Diploma",
  "PHD",
];

export const occupationOptions = [
  "Private Service",
  "Govt Service",
  "Public Sector / PSU",
  "Military/ Defence",
  "Self Employed",
  "Own Business",
  "Doctor",
  "Engineer",
  "CA",
  "Advocate",
  "Consultant",
  "Contractor",
];
